### ISSUE TITLE
possibility of a filesource producer

### ISSUE THREAD

**Issue by CraziFuzzy** [enternoescape/opendct#293]
I'm wondering if a producer could be easily made that simply reads from a 'file', and sends the stream to the consumer.  Reason I'm asking would be to leverage OpenDCT installed on a mini-pc (like a raspberry pi, for instance) connected to a hd-pvr, which would be presented as /dev/video0.  I was working up a very simple network encoder in perl to do this, but I think, especially once you've got a web config going for opendct, it might be a better option (keep everything familiar for existing opendct users).

**Comment by enternoescape** [comment]
That would be fairly trivial to do, but I really would rather actually support V4L if I'm going to go that route. I had plans to add that support, but my spare time lately has been dwindling.

**Comment by enternoescape** [comment]
I was working on a V4L2 network client specifically for the Raspberry Pi, that's much more light weight than OpenDCT but I stopped working on it after a few private conversations convinced me that the demand was rather low.

**Comment by CraziFuzzy** [comment]
Yeah, I've currently got a network encoder 'working' in an old v.1 pi right now - just with a relatively simple perl script to receive the commands, tune the channels, and launch and kill ffmpeg to do the actual transfers.  Working on the bench, and after I solder up my IR emitter (on breadboard right now) I'll have it moved to production for a while to make sure that's all good.  Would really rather run it through the uploadid method, but that's a lot more work than i feel like doing in perl.

I really don't know a lot about linux media in general, but I am at least using v4l2-ctl for setting the inputs on the hd-pvr.  I still need to put the discovery parts into my perl script and was probably going to add in the different crossbar types to the returned properties so it could be setup from in sage.  All in all this was scarily simple - so we'll see what I screwed up when i put it into production.

**Comment by enternoescape** [comment]
With the recent media server remuxer additions I did with SageTV, you could easily use the built in remuxer instead of FFmpeg. I will mention that at least in my own testing, Java was almost as fast as C++ on the pi and the scripting languages (like Perl) where noticeably slower. My takeaway there would be Perl might not be able to keep up with the data speeds needed for the SageTV media server, but a simple Java based network encoder would probably be fine. The media server functions of OpenDCT are fully contained in one class that could really be used in any Java program if it interests you.

**Comment by CraziFuzzy** [comment]
Yeah, that's why my current system is just using ffmpeg to handle the data flow, and is just managed by the Perl script.  I don't think I'd attempt to move the data with just perl.

**Comment by CraziFuzzy** [comment]
The uploadid method certainly would help with path management.

**Comment by enternoescape** [comment]
Perhaps when time permits, I'll finish my lighter V4L2 network encoder for the Raspberry Pi as it's own project with a very simple web interface to configure the basics, kind of like the Ethernet HDMI encoders I already have, but with 5.1 audio support. I also had/have plans to add support for the HD-PVR 2 on the RPi as a network encoder. I was able to get one of those working on a RPi after a little hassle by compiling the source code Hauppauge has freely available on their website. That's also on my list of things I hope to eventually get into the SageTV core so that Linux users can take advantage of the HD-PVR 2 (it does not have a V4L2 driver), but I don't want to "commit" to more than I can reasonably expect to do. I think the Schedules Direct piece is more important right now, so that's the fight I have chosen. :)

**Comment by CraziFuzzy** [comment]
So, I decided I was going to look into this a bit, and see what could be developed.  Just want to get some background before I dig in.  

1. What sort of native code is involved here (I'm not seeing much, besides may ccextractor), or do you suspect OpenDCT would run on a pi easily (looks like current rasbpian ships with Java 1.8.0_65)?
2. What parts would be needed to be added to OpenDCT to get very basic V4L2 support?
  a. I'm thinking a discoverer would be relatively simple, and could honestly get most of it's information simply browsing the /sys/class/video4linux tree.
  b. A tuner to handle IR blasting - I've built a blaster using the GPIO pins, and it works great simply calling irsend - no reason not to suspect that couldn't be simply wrapped into a tuner in opendct.  i believe actually configuring the input (simple call to v4l2-ctl) would also require to be in the tuner.
  c.  A producer to simply pull the stream from /dev/video0 and pass it to the consumer.

Am I anywhere close on the steps required?  This is from just some very high-level browsing of the code.

**Comment by CraziFuzzy** [comment]
Okay, so I'm testing out getting opendct up and running (just in it's current set of capabilities) on an old pi I've got laying around.  I have mostly gotten gradle massaged to make a .deb for the pi, but have a question about ffmpeg.  You're using the 2.8.1-1.1 javacpp presets, for which there is no linux-armhf jar.  There is, however, a 3.0.2-1.2 linux-armhf.jar.  Is there a specific reason for using the older version, or could it be moved up to the newer set?

**Comment by enternoescape** [comment]
You would also need to create a new discoverer to actually find and create instances of V4L2CaptureDevice. The discovery piece could use some simplification, but it is designed to be very modular.

I'll can get you a V4L2CaptureDevice.java device that will work about the same as GenericHttpCaptureDevice.java device. Instead of a manually provided HTTP address, it will dynamically get the V4L2 devices present and provide scripts for anything else you need. We don't really need anything special or native if you're going to use v4l2-ctl. I was planning on using the actual API, but based on your requirements, scripts will be sufficient. I'm not sure when I'll get around to this though.

JavaCPP 1.2 preset for FFmpeg 3.0.2 are currently broken for cross-platform between Windows and Linux. I have provided feedback on the related issue, but it's no one has updated the current Maven repos with the latest changes that should fix it. I tried to migrate over immediately when I saw the new versions were available and all kinds of problems cropped up related directly to them compiling the Windows version with one version of FFmpeg and the Linux version with a mostly incompatible version of FFmpeg. This could probably be worked around under ordinary circumstances, but specific things missing were causing entire libraries to fail to load. If this is mostly an effort to use an HD-PVR on a Pi, you really don't need FFmpeg anyway since the streams produced don't need any "massaging."

CCExtractor should be trivial to be compiled for armhf (I'm reasonably sure I have done it before). I just didn't do it since I we aren't packaging for armhf right now. If it can be pre-compiled, that's the route I have taken to save packaging time and to be more certain about consistency and so I don't need to fire up each environment to compile native code. I have scripts and documentation on how to update the binary on each platform if needed.

The last piece you might have some trouble with is JSW. The version used by OpenDCT is the last version that doesn't require the program to be GPL licensed. I don't think that project has anything for armhf.

**Comment by enternoescape** [comment]
Getting everything in its entirety working on the Pi is not impossible, but will probably require special treatment in Gradle and I would also like it to be able to optionally compile and run within an IDE on a Pi if possible. I'm still more in favor of a dedicated program that turns the Pi into a network encoder since OpenDCT will also detect and make available other network devices and if the user adds a few provided by the Pi, it might not be able to keep up depending on how many get added.

**Comment by CraziFuzzy** [comment]
I've actually done the gradle work and it seems to package up well.  Check my fork if you're interested.  There is an issue right now with gradle and armhf, in that it won't accept armhf as an arch setting in the deb task.  Arm works, but then dpkg whines about it unless you force it.  Ccextractor did compile up perfectly.  Only ffmpeg is a question right now, but using the media server consumer seems to work great so far.  I'm testing on an old gen 1 pi, so cpu is limiting - one atsc stream uses about 60% cpu, so obviously, it won't work on a gen 1 for a full hdhr, but a single hdpvr (my ultimate goal) would likely work great.

**Comment by enternoescape** [comment]
Interesting. Thanks for doing all the leg work and testing of feasibility. I really thought it would be too much for the Pi.

If you're wondering, the issue with the JavaCPP FFmpeg preset is here:
https://github.com/bytedeco/javacpp-presets/issues/225
