### ISSUE TITLE
Failover on can't open port 9000

### ISSUE THREAD

**Issue by CraziFuzzy** [enternoescape/opendct#311]
Since the port opendct uses is not required to be 9000, and since Logitech Media Server DOES use 9000, it'd be nice if when opendct fails to open 9000, it fails over to the 9001, and so on.  LMS is a rather common/highly used docker container, so this conflict is sure to come up more than just in my case.

**Comment by enternoescape** [comment]
The reason the program fails outright instead of adjusting the port is because SageTV will not be able to find the capture device if the user is having a problem with their ports being blocked. This might be ok the first time the program is started and a capture device is found, but it could be a disaster if it adjusts ports without any interaction on the user's part and they start missing recordings.

**Comment by enternoescape** [comment]
I will admit that I should have chosen a better port, but at the time it didn't occur to me that was a commonly used port. Often I do look up ports to make sure they don't have a very common use, but in this case I had not, and it is causing problems for some users.

**Comment by enternoescape** [comment]
So after all of that explanation, I think this is harmless if the capture device isn't already established. Otherwise I would want it to still crash the container. Otherwise how would the average user know there's a problem until they start missing recordings.

**Comment by CraziFuzzy** [comment]
So here's a thought - a process that tests the port designated in sagetv.new.device.socket_server_shared_port, and it it is open, it stays the same, but if not, it decrements down until it finds a new port (down because up from default would move into the server_port_low-high range), and once it finds an open port, sets that property to that value.  If this is done prior to the first detection, than each device would be set up with the new open port number, but already configured devices would continue using their encoder_listen_port value..

Or, we just go ahead and change the default from 9000 to something else (8999 perhaps) and it'll at least help out future users who might have the conflict.

**Comment by enternoescape** [comment]
I did a bit of a hybrid of your suggestion. It's ok to go up with the ports since the code will work around a port being assigned within the port ranges. Those are only used if you turn on incremental port assignment (which is off by default). Basically if the port is in use and a port has never been assigned to the capture device, the code will increment the port and keep trying until it hits 2^16. In the unlikely event that it actually gets there, then we use 0 which tells Java to auto-assign. However we get to using a valid port, once we find one that works, it's saved. If incremental port assignment is turned off, the port is new and the default port is not yet in use, but another port has already been opened, that other port will become the new default port and saved in sagetv.new.device.socket_server_shared_port. Basically the only way the port number will ever change is if the device was previously unknown.

**Comment by enternoescape** [comment]
The new code is now in the master if you want to try it out ahead of the next release.

**Comment by enternoescape** [comment]
Resolved in pull #312.
